apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: contosobooks.azurecr.io/demoapp:20220512180036
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: db-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
data:
  password: U2VhdHRsZTgwMA== #arcadmin
  username: YXJjYWRtaW4= #Seattle800
kind: Secret
metadata:
  name: db-login-secret
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v4
kind: SqlManagedInstance
metadata:
  name: db
spec:
  dev: true
  licenseType: LicenseIncluded
  tier: BusinessCritical
  replicas: 3
  security: 
    adminLoginSecret: db-login-secret
  scheduling:
    default:
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
  services:
    primary:
      type: LoadBalancer
  storage:
    data:
      volumes:
      - className: default
        size: 5Gi
    datalogs:
      volumes:
      - className: default
        size: 5Gi
    logs:
      volumes:
      - className: default
        size: 5Gi